### PR TITLE
Class and Function Documentation

### PR DESCRIPTION
**Pull request by rgill02**
In the process of adding class and function documentation

### CODE REVIEW

**Comment by GrahamGoudeau21** [comment]
How are you making those function/class separators?  By hand?

**Comment by rgill02** [comment]
Copy and paste

**Comment by GrahamGoudeau21** [comment]
We maybe want a more sustainable way to have function/class separators, I don't know.  I'm still not totally sure we should have them at all, but it's fine to keep them in for now.

**Comment by GrahamGoudeau21** [comment]
Also, I have a version of this PR with a cleaned-up history

**Pull request merged**
